version: 2
jobs:
  test-unit:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo 'unit test'
  test-e2e:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo 'e2e unit test'
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - run: echo 'deploy'

workflows:
  version: 2
  build:
    jobs:
      - test-unit
      - test-e2e
      - deploy:
          requires:
            - test-unit
            - test-e2e
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
